[package]
name = "luisa-compute"
version = "0.1.0"
edition = "2021"

[dependencies]
luisa-compute-sys = { path = "luisa-compute-sys" }
serde_json = "1.0"

[workspace]
members = [
    "luisa-compute-sys"
]

[features]
default = []
cuda = []
dx = []
vk = []
llvm = []
ispc = []
python = []
