[package]
name = "luisa_compute_sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.60"
cmake = "0.1.48"
luisa_compute_api_types = {path = "LuisaCompute/src/api/luisa_compute_api_types"}

[features]
default = []
cuda = []
dx = []
vk = []
llvm = []
ispc = []
python = []
_cpp = []

