[package]
name = "luisa-compute-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1"
quote = "1.0"
proc-macro2 = "1"
prettyplease = "0.1.17"