[package]
name = "luisa_compute"
version = "0.1.0"
edition = "2021"

[dependencies]
luisa_compute_sys = { path = "../luisa_compute_sys", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"
luisa_compute_ir = { path = "../luisa_compute_sys/LuisaCompute/src/ir/luisa_compute_ir" }
luisa_compute_api_types = { path = "../luisa_compute_sys/LuisaCompute/src/api/luisa_compute_api_types" }
luisa_compute_derive = { path = "../luisa_compute_derive" }
luisa_compute_derive_impl = { path = "../luisa_compute_derive_impl" }

[features]
default = []
_cpp = ["luisa_compute_sys"]
cuda = ["_cpp"]
dx = ["_cpp"]
metal = ["_cpp"]
vulkan = ["_cpp"]
llvm = ["_cpp"]
