[package]
name = "luisa_compute_derive_impl"
version = "0.1.1-alpha.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version="2",features=["full"]}
quote = "1.0"
proc-macro2 = "1"
prettyplease = "0.2.4"

