name: Rust

on:
  push:
    branches: [ "main", "next" ]
  pull_request:
    branches: [ "main", "next"  ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: "Install Dependencies"
      run: |
        sudo apt-get purge --auto-remove cmake
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get -y install cmake
        sudo apt-get -y install gcc-11 g++-11 build-essential ninja-build git file libopencv-dev uuid-dev libglfw3-dev libxinerama-dev libxcursor-dev libxi-dev
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 14
    # - name: "Setup CUDA"
    #   uses: Jimver/cuda-toolkit@v0.2.8
    #   with:
    #     linux-local-args: '["--toolkit"]'
    - name: "Build"
      run: CC=clang-14 CXX=clang++-14 cargo build --verbose --release
    - name: "Run Tests"
      run: |
        RUST_BACKTRACE=1 CC=clang-14 CXX=clang++-14 cargo test --verbose --release
        RUST_BACKTRACE=1 bash run_tests.sh
#     - name: "Run CUDA Tests"
#       run: CC=clang-14 CXX=clang++-14 LUISA_TEST_DEVICE=cuda cargo test --features cuda --verbose --release 
